name: Bug 反馈
description: 创建一个 issue 帮助改进这个项目
title: "[BUG] <在这里输入你的标题>"
labels: ["Bug"]
assignees:
  - teamssix
body:
  - type: markdown
    attributes:
      value: |
        谢谢您花时间提交这份 issue (Thanks for taking the time to fill out this bug report!)
  - type: textarea
    id: what-happened
    attributes:
      label: 描述你遇到的问题 (What happened?)
      value: "简单描述你所遇到的问题"
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: 操作系统 (Operating System)
      description: 你在哪种操作系统下运行的 CF ？(Which operating system you are running the CF in?)
      options:
        - MacOS
        - Linux
        - Windows
    validations:
      required: true
  - type: dropdown
    id: system type
    attributes:
      label: 系统类型 (System Type)
      description: 你在哪种系统类型下运行的 CF ？(What type of system are you running CF on?)
      options:
        - amd64
        - amd32
        - arm64
        - arm32
    validations:
      required: true  
  - type: dropdown
    id: cf version
    attributes:
      label: 版本 (Version)
      description: 你运行的是 CF 的哪个版本？(What version of our software are you running?)
      options:
        - 0.3.4
        - 0.3.3
        - 0.3.2
        - 0.3.1
        - 0.3.0
        - 0.2.x
        - 0.1.x
        - 0.0.x
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. 这将自动格式化为代码，因此无需背板。
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
