name: 新功能反馈
description: 创建一个 issue 帮助改进这个项目
title: "[Feat] <在这里输入你的标题>"
labels: ["feat"]
assignees:
  - teamssix
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间提交这份 issue (Thanks for taking the time to fill out this bug report! )
  - type: textarea
    id: new-features
    attributes:
      label: 描述你想反馈的需求 (Describe your needs)
      value: "详细描述你想反馈的需求，例如希望增加天翼云的相关操作。"
    validations:
      required: true
  - type: textarea
    attributes:
      label: 补充信息 (Anything else?)
      description: |
        链接？参考资料？任何可以给我们提供更多关于你所遇到的问题的背景资料的东西
        Links? References? Anything that will give us more context about the issue you are encountering!
        
        提示：你可以通过点击这个区域来突出显示它，然后将文件拖入，从而附上图片或其他文件。
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
